# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout backend repo
        uses: actions/checkout@v3
        with:
          repository: santa-close/santa-close-server
          path: ./back

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build santa_close_design-system
        run: yarn build
        env:
          SCHEMA_PATH: ../../back/app/src/main/resources/graphql/schema.graphql

      - name: Lint check
        run: yarn lint

      - name: Type check
        run: yarn type-check
